version: "3.1"
services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
